### ISSUE TITLE
자유대화 데이터셋으로 학습된 결과를 확인할 수 있을까요?

### ISSUE THREAD

**Issue by seastar105** [hwRG/FastSpeech2-Pytorch-Korean-Multi-Speaker#1]
pretrain된 모델 성능을 체크해보고 싶은데 공개된 모델이나 샘플이 있을까요??

aihub 자유대화 데이터셋이 인식을 염두에 두고 공개됐던 데이터셋으로 기억해서 성능 확인을 해볼 수 있으면 정말 좋을 거 같습니다.

**Comment by hwRG** [comment]
안녕하세요 seastar105님.

Demo 디렉토리에 pre-trained model로 합성한 오디오와 원본 오디오를 엮어 업로드해두었습니다.

말씀하신 대로 데이터셋이 인식용으로 구축되었고, 스마트폰으로 녹음 되었기에 많이 걱정되었으나,
실사용은 아니더라도 간단한 pre-trained 용도로는 충분한 것을 확인할 수 있었습니다.

감사합니다.

**Comment by hwRG** [comment]
> 

안녕하세요 seastar105님.

Demo 디렉토리에 pre-trained model로 합성한 오디오와 원본 오디오를 엮어 업로드해두었습니다.

말씀하신 대로 데이터셋이 인식용으로 구축되었고, 스마트폰으로 녹음 되었기에 많이 걱정되었으나,
실사용은 아니더라도 간단한 pre-trained 용도로는 충분한 것을 확인할 수 있었습니다.

감사합니다.

**Comment by seastar105** [comment]
@hwRG midTerm Demo랑 pretrained demo랑 같은 epoch만큼 훈련된 모델인가요? 둘 다 unseen utterance 같은데 차이가 꽤 있네요. 제 생각보다 괜찮은 성능을 보여주네요. 감사합니다.

**Comment by hwRG** [comment]
@seastar105 

Mid Term은 fine-tune 결과물이라 pre-train 보다 낮은 품질을 보입니다. 그리고 Mid Term 시점보다 데이터셋을 개선(데이터 선별, 에포크 수 등) 하여 pre-train 최종 결과물은 더 안정적인 품질을 제공합니다. 

감사합니다.
